inputs:
  - name: local
    metadata: "data/metadata.tsv"
    sequences: "data/sequences.fasta"

exclude: "exclude.txt"
reference: "reference_cytb.gb"
auspice_config: "auspice_config.json"
description: "description.md"
color_ordering: "color_ordering.tsv"
color_schemes: "color_schemes.tsv"

strain_id_field: "accession"

filter:
  subsample_max_sequences: 10000
  min_length: 1000

ancestral:
  inference: "joint"

traits:
  columns:
    - family
    - order_name
    - country
  sampling_bias_correction: 3
  branch_labels:
    - family
    - order_name
